### ISSUE TITLE
Possible to add a license?

### ISSUE THREAD

**Issue by tomwardill** [robinolejnik/mini-usb-radio-interface#1]
Discovered this project while researching how to design my own, with exactly the same purpose (Packet radio interface).

I'd like to get a small run of the boards made for myself and other people in [OARC](oarc.uk), on a non-profit/commercial basis.

Would it be possible to either get permission to do that, or to get a license added to the project?

Thanks!

**Comment by robinolejnik** [comment]
Hi Tom,

I just added the MIT license. Have fun with the board! :)
I also updated everything to KiCad 8.
If you want to do your own PCB with the CM108, you can find it's symbol in my [KiCad library](https://github.com/robinolejnik/kicad-libraries)

Kind Regards
Robin

**Comment by tomwardill** [comment]
@robinolejnik That's amazing, thank you! I'll get some boards made up and let you know how it goes :)
